"""Code lists, source registry, and federal category definitions.

All code lists are generated by ``scripts/build_codelists.py`` from official public
files; see ``docs/sources.md``.
"""
from __future__ import annotations

import json
from functools import lru_cache
from importlib import resources

import pandas as pd
import yaml

_PKG = "frailty_toolkit.definitions"


def _read_text(*parts: str) -> str:
    return resources.files(_PKG).joinpath(*parts).read_text(encoding="utf-8")


@lru_cache(maxsize=1)
def load_codes() -> pd.DataFrame:
    """One row per (component_id, code_system, code) with description and source_id."""
    with resources.files(_PKG).joinpath("codelists", "codes.csv").open("r", encoding="utf-8") as f:
        return pd.read_csv(f, dtype=str, keep_default_na=False)


@lru_cache(maxsize=1)
def load_components() -> pd.DataFrame:
    with resources.files(_PKG).joinpath("codelists", "components.csv").open("r", encoding="utf-8") as f:
        return pd.read_csv(f, dtype={"n_codes": int}, keep_default_na=False)


@lru_cache(maxsize=1)
def load_sources() -> dict:
    return json.loads(_read_text("codelists", "sources.json"))


@lru_cache(maxsize=1)
def load_category_definitions() -> dict:
    return yaml.safe_load(_read_text("categories.yaml"))


FEDERAL_CATEGORY_ORDER = [
    "blind_or_disabled",
    "substance_use_disorder",
    "disabling_mental_disorder",
    "physical_idd_disability_adl",
    "serious_or_complex_medical",
]


def split_component_ref(ref: str) -> tuple[str, str | None]:
    """'component:PREFIX' -> ('component', 'PREFIX'); 'component' -> ('component', None)."""
    if ":" in ref:
        cid, prefix = ref.split(":", 1)
        return cid, prefix.replace(".", "").upper()
    return ref, None


def component_codes(ref: str) -> pd.DataFrame:
    """Codes for a component reference, honouring an optional ':PREFIX' restriction."""
    cid, prefix = split_component_ref(ref)
    codes = load_codes()
    out = codes[codes["component_id"] == cid]
    if prefix:
        out = out[out["code"].str.startswith(prefix)]
    return out


__all__ = [
    "FEDERAL_CATEGORY_ORDER",
    "component_codes",
    "load_category_definitions",
    "load_codes",
    "load_components",
    "load_sources",
    "split_component_ref",
]
