#!/usr/bin/env python3
"""Render docs/sources.md from codelists/sources.json, components.csv, and categories.yaml,
so the documentation cannot drift from the bundled lists."""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from frailty_toolkit.definitions import load_components, load_sources  # noqa: E402
from frailty_toolkit.validation.public_checks import category_source_table  # noqa: E402

HEADER = """# Code-list sources

This file is generated by `scripts/render_sources_md.py`; do not edit it by hand.

Every code in `frailty_toolkit/definitions/codelists/codes.csv` carries a `source_id` that
points to one entry below. Codes were either (a) read from a downloaded official file, or
(b) selected from an official file by a prefix or range written in
`definitions/specs/selections.yaml` (the code and its description still come from the
file), or (c) individually cited to a CMS manual or ResDAC table in
`definitions/specs/cited_codes.yaml`. No NCQA value sets are used. The public-data
provenance check (`python -m frailty_toolkit.validation.public_checks --cache-dir ...`)
re-opens each source file and confirms that every code attributed to it is present.

ICD-10-CM codes are validated against the union of the FY2024-FY2027 CMS order files so
that retrospective evaluation on 2024-2025 claims sees codes valid on the date of service.
Tokens printed in a CCW PDF that are not valid in any of those four fiscal years (codes
deleted before FY2024) are dropped and listed in `codelists/build_report.json`.

## Not bundled

* The Harvard T.H. Chan School of Public Health medically frail workbook that Washington
  HCA adopted (https://www.hca.wa.gov/assets/billers-and-providers/medically-frail-code-list.xlsx,
  last updated 2026-07-31). Its cover page permits free use by state agencies with
  attribution and requires for-profit entities to obtain a license from Harvard's Office of
  Technology Development. A state agency can load it at run time through
  `external_code_lists`.
* Ohio's 1,935-code ODM list, which ODM had not posted as of 2026-09-29.
* NDC lists other than the CCW medication-for-OUD lists. States that want antipsychotic
  or other pharmacy markers must add a cited list.
* A SAMHSA code list for serious mental illness. SAMHSA and ISMICC define SMI by functional
  impairment rather than by a code list; the IFC names ISMICC, DSM-5, and ICD-10 as
  resources (91 FR 33375) without adopting a list. The disabling-mental-disorder category
  therefore uses CCW algorithms for the conditions the IFC names.

"""


def main():
    src = load_sources()
    comps = load_components()
    lines = [HEADER, "## Source registry\n",
             "| source_id | Title | Publisher | Version | Accessed | URL | SHA-256 of file |",
             "|---|---|---|---|---|---|---|"]
    for sid, s in src.items():
        sha = s.get("sha256", "")
        lines.append(f"| `{sid}` | {s['title']} | {s['publisher']} | {s['version']} | {s.get('access_date', '')} | "
                     f"{s['url']} | {sha[:16] + '...' if sha else 'n/a'} |")
    lines += ["", "## Category to component to source\n",
              "| Category | CFR | Role | Component | Codes | Source(s) |", "|---|---|---|---|---|---|"]
    for r in category_source_table().itertuples():
        lines.append(f"| {r.category} | {r.cfr} | {r.role} | `{r.component}` ({r.label}) | {r.n_codes} | "
                     f"{r.sources} |")
    lines += ["", "## All components\n", "| Component | Label | System | Source | Derivation | Codes |",
              "|---|---|---|---|---|---|"]
    for r in comps.itertuples():
        der = str(r.derivation).replace("|", "/")[:140]
        lines.append(f"| `{r.component_id}` | {r.label} | {r.code_system} | {r.source_id} | {der} | {r.n_codes} |")
    (REPO / "docs" / "sources.md").write_text("\n".join(lines) + "\n")
    print("wrote docs/sources.md")


if __name__ == "__main__":
    main()
